#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Gun menu :
/gui/addMenu beam Energy
/gui/addButton beam "70 MeV"  "/gun/energy 70 MeV"
/gui/addButton beam "100 MeV"  "/gun/energy 100 MeV"
/gui/addButton beam "130 MeV"  "/gun/energy 130 MeV"
/gui/addButton beam "160 MeV"  "/gun/energy 160 MeV"
/gui/addButton beam "190 MeV"  "/gun/energy 190 MeV"
/gui/addButton beam "220 MeV"  "/gun/energy 220 MeV"
/gui/addButton beam "250 MeV"  "/gun/energy 250 MeV"
#
# Particle menu :
/gui/addMenu particle Particle
/gui/addButton particle "proton"  "/gun/particle proton"
/gui/addButton particle "neutron" "/gun/particle neutron"
/gui/addButton particle "e-"      "/gun/particle e-"
#
# Model menu :
/gui/addMenu model Model
/gui/addButton model "Cu"  "/PFC/setModelNum 0"
/gui/addButton model "Cu_KA" "/PFC/setModelNum 1" 
/gui/addButton model "Cu_KA_AgKA" "/PFC/setModelNum 2"
#
# Kapton Thickness menu :
/gui/addMenu kapthick Insulator
/gui/addButton kapthick "S59" "/PFC/setKaptonThickness 50"
/gui/addButton kapthick "S100" "/PFC/setKaptonThickness 100"
/gui/addButton kapthick "S200" "/PFC/setKaptonThickness 200"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
/run/printProgress 100
#
# User defined icon :
/gui/addIcon "Run beam on" user_icon "/run/beamOn 1" run.png 
